name: Release

on:
  push:
    tags:
      - '*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir disciple-tools-setup-wizard
          cp -r disciple-tools-setup-wizard.php admin rest-api languages spinner.svg version-control.json LICENSE SECURITY.md disciple-tools-setup-wizard/
          zip -r disciple-tools-setup-wizard.zip disciple-tools-setup-wizard
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./disciple-tools-setup-wizard.zip
          generate_release_notes: true
